### ISSUE TITLE
Проверить ДЗ 5

### ISSUE THREAD

**Issue by HelgaJava** [HelgaJava/gir-HomeWork5Megafon#1]
Есть сомнения в реализации дополнительных опций в тарифах. Сначала хотела реализовать все на  true/false. Например: unlimitedInternetForServices = true или false. Но потом подумала, что слишком много проверок надо делать при выводе информации. Поэтому сделала с описанием дополнительных опций. Но сомнения все равно остались. Была еще мысль реализовать это все с доп. классом типа options. Сделать массив, заполнить его этими доп. опциями, а при формировании самого тарифа доставать оттуда конкретный элемент. В общем буду ждать от вас замечаний.

**Comment by coursar** [comment]
Пока так достаточно, когда будем делать веб-сервисы, будем делать через список опций.

**Comment by HelgaJava** [comment]
Интересен ваш подход к этой задаче. Как бы вы реализовали эту задачу на той базе знаний, которая имелась на момент этого ДЗ?

**Comment by coursar** [comment]
Сначала бы полями типами `unlimitedUnternet`, при развитии проекта, собрал бы всё в список опций.
